schema_version: 1

context:
  name: neapolitan
  version: "25.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/neapolitan-${{ version }}.tar.gz
  sha256: e5f1692c6d5807143f48635e351f62f0921d491efa6de8906e9a5ca22104a877

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - django
    - django-filter
    # Django on win requires python-tzdata
    - python-tzdata

tests:
  - python:
      imports:
        - neapolitan
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Neapolitan is a quick CRUD views for Django.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/carltongibson/neapolitan
  documentation: https://noumenal.es/neapolitan/

extra:
  recipe-maintainers:
    - thewchan
